export type EventDetails = {
    id: string | number;
    organizerId: string | number;
    projectId: string | number;
    title: string;
    month: string;
    day: string;
    dateLabel: string;
    timeLabel: string;
    locationName: string;
    address: string;
    organizerLabel: string;
    organizerName: string;
    organizerDescription: string;
    aboutLabel: string;
    description: string[];
    primaryActionLabel: string;
    secondaryActionLabel: string;
    gallery: string[];
};
