services:
    campus-front:
        build:
            context: .
            args:
                VITE_API_URL: ${VITE_API_URL:-http://localhost}
        image: campus-front:latest
        ports:
            - "${FRONTEND_PORT:-8080}:80"
        restart: unless-stopped
